export let products = [
  {
    "name": "Premium Wireless Headphones",
    "brand": "AudioTech",
    "price": 99.99,
    "description": "Experience crystal-clear sound with these premium wireless headphones. Perfect for music lovers and audiophiles alike.",
    "image": "/assets/Premium_wireless_headphones.jpeg",
    "color": "Black",
    "connectivity": "Bluetooth 5.0",
    "battery_life": "Up to 20 hours",
    "noise_cancellation": true,
    "compatibility": "iOS, Android, Windows",
    "warranty": "1 year",
    "weight": "200 grams",
    "dimensions": "8 x 6 x 2 inches"
  },
  {
    "name": "Smart Watch - Fitness Tracker",
    "brand": "FitMotion",
    "price": 79.99,
    "description": "Stay connected and track your fitness goals with this sleek smartwatch. Monitor your steps, heart rate, and more.",
    "image": "/assets/Smart_watch_fitness_tracker.jpeg",
    "color": "Silver",
    "display_type": "LCD",
    "water_resistance": "IP68",
    "strap_material": "Silicone",
    "features": ["Heart rate monitor", "Sleep tracker", "Notifications"],
    "compatibility": "iOS, Android",
    "warranty": "2 years",
    "weight": "50 grams",
    "dimensions": "1.5 x 1.5 x 0.5 inches"
  },
  {
    "name": "Classic Leather Wallet",
    "brand": "UrbanLeather",
    "price": 29.99,
    "description": "Upgrade your style with this timeless leather wallet. Slim design with multiple card slots and a cash pocket.",
    "image": "/assets/Classic_leather_wallet.jpeg",
    "color": "Brown",
    "material": "Genuine leather",
    "capacity": "6 cards + cash",
    "closure": "Bi-fold",
    "dimensions": "4.5 x 3.5 x 0.5 inches",
    "features": ["RFID blocking", "Slim design"],
    "warranty": "Lifetime"
  },
  {
    "name": "Stainless Steel Water Bottle",
    "brand": "HydraLife",
    "price": 19.99,
    "description": "Stay hydrated on the go with this durable stainless steel water bottle. Keeps your drinks cold for hours.",
    "image": "/assets/Stainless_steel_water_bottle.jpeg",
    "color": "Silver",
    "material": "Stainless steel",
    "capacity": "750ml",
    "insulation": "Double-wall vacuum insulation",
    "features": ["BPA-free", "Leak-proof cap"],
    "dimensions": "10 x 3 inches",
    "weight": "300 grams",
    "warranty": "2 years"
  },
  {
    "name": "Essential Oil Diffuser",
    "brand": "AromaVita",
    "price": 39.99,
    "description": "Create a relaxing atmosphere in your home with this essential oil diffuser. Enjoy the benefits of aromatherapy.",
    "image": "/assets/Essential_oil_diffuser.jpeg",
    "color": "Wood Grain",
    "material": "PP + ABS",
    "capacity": "400ml",
    "mist_output": "30ml/hour",
    "lighting_options": ["7 LED colors", "Dimmable"],
    "timer_settings": ["1hr, 3hr, 6hr, continuous"],
    "dimensions": "6 x 6 x 8 inches",
    "weight": "400 grams",
    "warranty": "1 year"
  },
  {
    "name": "Cotton Blend T-Shirt",
    "brand": "CasualWear",
    "price": 14.99,
    "description": "Upgrade your casual wardrobe with this comfortable cotton blend t-shirt. Available in various colors.",
    "image": "/assets/Cotton_blend_t-shirt.jpeg",
    "color": "White",
    "material": "Cotton-polyester blend",
    "sizes": ["S", "M", "L", "XL"],
    "fit": "Regular fit",
    "care_instructions": "Machine wash cold, tumble dry low",
    "warranty": "30 days"
  },
  {
    "name": "Wireless Charging Pad",
    "brand": "ChargeUp",
    "price": 34.99,
    "description": "Charge your compatible devices wirelessly with this convenient charging pad. Sleek design with LED indicator.",
    "image": "/assets/Wireless_charging_pad.jpeg",
    "color": "Black",
    "compatibility": "Qi-compatible devices",
    "output": "10W",
    "input": "USB-C",
    "features": ["Anti-slip surface", "Overcharge protection"],
    "dimensions": "3.9 x 3.9 x 0.4 inches",
    "weight": "100 grams",
    "warranty": "1 year"
  },
  {
    "name": "Resistance Bands Set",
    "brand": "FlexFit",
    "price": 49.99,
    "description": "Enhance your workout routine with this set of resistance bands. Perfect for strength training and rehabilitation exercises.",
    "image": "/assets/Resistance_bands_set.jpeg",
    "material": "Latex",
    "levels": "5 resistance levels",
    "includes": ["5 bands", "Door anchor", "Ankle straps", "Carrying bag"],
    "dimensions": "12 x 2 inches (each band)",
    "weight": "500 grams",
    "warranty": "2 years"
  },
  {
    "name": "Non-Stick Cooking Pan",
    "brand": "MasterChef",
    "price": 24.99,
    "description": "Cook with ease using this non-stick cooking pan. Durable construction and easy to clean.",
    "image": "/assets/Non-stick_cooking_pan.jpeg",
    "color": "Black",
    "material": "Aluminum",
    "size": "10 inches",
    "coating": "PFOA-free non-stick coating",
    "handle": "Heat-resistant silicone handle",
    "dishwasher_safe": true,
    "warranty": "3 years"
  },
  {
    "name": "Polarized Sunglasses",
    "brand": "SunBlock",
    "price": 59.99,
    "description": "Protect your eyes in style with these polarized sunglasses. Perfect for outdoor activities and everyday wear.",
    "image": "/assets/Polarized_sunglasses.jpeg",
    "color": "Matte Black",
    "lens_material": "Polarized TAC",
    "frame_material": "TR90",
    "uv_protection": "100% UV400 protection",
    "polarization": true,
    "includes": ["Hard case", "Cleaning cloth"],
    "warranty": "1 year"
  }
]